@startuml
start

:Пацієнт обирає час та лікаря;
:Адміністратор створює запис у системі;

if (Пацієнт з'явився на прийом?) then (так)
  :Проведення первинного огляду;
  :Встановлення діагнозу;
  
  if (Потрібне додаткове обстеження?) then (так)
    :Проведення рентген-діагностики;
  else (ні)
  endif

  :Складання плану лікування;
  :Збереження плану в картку пацієнта;
  stop
else (ні)
  :Скасування запису;
  stop
endif

@endum