@startuml
left to right direction
actor "Owner" as ow
actor "User" as us

rectangle TripAdvisor {
  usecase "Add New Restaurant" as UC1
  usecase "Add Review" as UC2
  usecase "Moderate Review" as UC3
}

ow -- UC1
us -- UC2
UC2 ..> UC3 : <<include>>
@enduml